name: Add Reviewers

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Reviewers
        uses: azqazq195/actions.add-reviewers@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
